#!/bin/zsh

. $HOME/.zshrc >> /dev/null

function setItem () {
  command=$1
  name=$2
  value=$3
  option=""

  if [ "$command" = "yarn" ]; then
    option="config"
  fi

  
  if [ "$command" != "yarn" ]; then
    echo 'Config '${command}' Source: '${name}
  fi

  $command $option set $name $value
} 

# Config Function
function config () {
  command=$1
  which $command >> /dev/null
  if [ ! $? -eq 0 ]; then
    echo 'Invalid Command:'${command}
    return
  fi

  setItem $command registry https://registry.npm.taobao.org
  # setItem $command disturl https://npm.taobao.org/dist # node-gyp 编译依赖的 node 源镜像
  # setItem $command chromedriver_cdnurl http://cdn.npm.taobao.org/dist/chromedriver # chromedriver 二进制包镜像
  # setItem $command operadriver_cdnurl http://cdn.npm.taobao.org/dist/operadriver # operadriver 二进制包镜像
  # setItem $command phantomjs_cdnurl http://cdn.npm.taobao.org/dist/phantomjs # phantomjs 二进制包镜像
  # setItem $command sass_binary_site http://cdn.npm.taobao.org/dist/node-sass # node-sass 二进制包镜像
  # setItem $command electron_mirror http://cdn.npm.taobao.org/dist/electron/ # electron 二进制包镜像

  # $command cache clean # 清空缓存
}

function install () {
  package=$1

  if [ "$1" = "" ]; then
    exit 0
  fi

  echo -ne "正在安装: ${packages} ...\r"
  npm i -g $package # 2&>1 >> /dev/null

  if [ ! $? -eq 0 ]; then 
    echo -ne "安装 ${package} 失败\r"
  else
    echo -ne "安装 ${package} 成功\r"
  fi

  echo -ne "\n"
}


which nvm >> /dev/null
if [ $? -eq 0 ]; then
  echo "You have install nvm."
  return
fi

# Install nvm
echo "Install node version manager ..."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash

# add nvm env to .zshrc and Load nvm
echo "Load nvm enviroment ..."
echo "NVM_DIR=\"$HOME/.nvm\"" >> $HOME/.zshrc
echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $HOME/.zshrc
. $HOME/.zshrc

# Install Node
echo "Install Node v11 by using nvm"
nvm install v11

echo "Loading node ..."
nvm use v11

echo "切换 NPM 源 ..."
config npm
config yarn

echo "安装常用软件..."
install cnpm
install nrm
install serve
install projj

